<div class="row">

    <div class="col-md-12">
        Liste des meetups

        <ul>
          <?php foreach ($this->meetups as $meetup): ?>
            <a href="<?= $this->url('meetup', ['id' => $meetup->getId()]) ?>">
              <li><?= $meetup->getTitle() ?></li>
            </a>
          <?php endforeach; ?>
        </ul>

        <a href="<?= $this->url('home/add'); ?>" class="btn btn-primary">Add new</a>
    </div>

  </div>
